---
- name: Add mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip }} {{ item.namelong }} {{ item.nameshort }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.nameshort }}"
  with_items:
  - { ip: 192.168.20.9, namelong: vg-silk-01.local, nameshort: vg-silk-01 }
  - { ip: 192.168.20.10, namelong: vg-silk-02.local, nameshort: vg-silk-02 }
  - { ip: 192.168.20.11, namelong: vg-silk-03.local, nameshort: vg-silk-03 }
  when: add_host_entries
