---
- name: "Boot all hosts"
  gather_facts: true
  hosts:  all
  become: yes
  vars:
    add_host_entries: true
    add_resolv_entries: true
  pre_tasks:
  - name: "Setting hostname"
    shell: "hostnamectl set-hostname {{ inventory_hostname }}"
  roles:
    - common
    - silk
# - name: "Install silk"
#   gather_facts: true
#   hosts:  vg-silk-03
#   become: yes
#   vars:
#     add_host_entries: true
#     add_resolv_entries: true
#   pre_tasks:
#   - name: "Setting hostname"
#     shell: "hostnamectl set-hostname {{ inventory_hostname }}"
#   roles:
#     - silk
